# Generated by Django 2.2.5 on 2022-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='comprado',
            new_name='checked',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
