# Generated by Django 2.2.5 on 2022-06-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20220610_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gifts',
        ),
        migrations.AddField(
            model_name='gift',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.Event'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
